spring.application.name=rabbitmq-producer

server.port=8080

management.server.port=9080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ACTUATOR ENDPOINTS
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

info.app.name=Spring-Boot-RabbitMQ-Guide
info.app.version=0.0.1-SNAPSHOT
info.app.git.commit=abc123

# CONFIRMATION-RETURN
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true


# Direct
direct.exchange = direct.exchange

# Direct Exchange Queue
orders.queue = orders.queue
orders.route = orders.route

# Routing Keys
notification.queue = notification.queue
notification.route = notification.route

# Fanout
fanout.exchange = fanout.exchange

# Fanout Exchange Queue
email.queue = email.queue
sms.queue = sms.queue
push.queue = push.queue

# Topic
topic.exchange = topic.exchange

# Topic Exchange Queue
user.signup.queue = user.signup.queue
user.login.queue = user.login.queue
system.error.queue = system.error.queue

# Topic Routing Keys
user.signup.route=user.signup.route
user.login.route=user.login.route
system.error.route=system.error.route

# Headers
headers.exchange=headers.exchange

# Headers Priority Exchange Queue
priority.high.queue = priority.high.queue
priority.low.queue = priority.low.queue
